# Generated by Django 3.2 on 2021-04-14 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=264, unique=True)),
                ('code', models.CharField(max_length=264, unique=True)),
                ('validate', models.DateField()),
                ('mac_address', models.CharField(max_length=264, unique=True)),
            ],
        ),
    ]
