version: '3'
services:
    activation_tool:
        build: .
        ports:
            - "8000:8000"
        volumes: 
            - /data:/data
        restart: always
        
        container_name: activation_tool
        